//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Caja
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int Id_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Cedula_Cliente { get; set; }
        public Nullable<int> Id_Seguro { get; set; }
        public string Poliza { get; set; }
        public string Telefono { get; set; }
    }
}
