//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Caja
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int Id_Empleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Cedula_Empleado { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
    }
}
