//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Caja
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontoInicial
    {
        public int Id { get; set; }
        public decimal Monto_Inicial { get; set; }
        public string Fecha { get; set; }
    }
}
