//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Caja
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        public int Id_Servicio { get; set; }
        public string Nombre_Servicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
