//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaIntegracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public int Id_Factura { get; set; }
        public int Id_Cliente { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Seguro { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    }
}
