//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaIntegracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURO
    {
        public int Id_Seguro { get; set; }
        public string Nombre_Seguro { get; set; }
        public Nullable<decimal> Des_Porcentaje { get; set; }
    }
}
