//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Caja.WSPrueba {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPrueba.WSBDSoap")]
    public interface WSBDSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        hospital.Caja.WSPrueba.HelloWorldResponse HelloWorld(hospital.Caja.WSPrueba.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<hospital.Caja.WSPrueba.HelloWorldResponse> HelloWorldAsync(hospital.Caja.WSPrueba.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearFactura", ReplyAction="*")]
        hospital.Caja.WSPrueba.crearFacturaResponse crearFactura(hospital.Caja.WSPrueba.crearFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<hospital.Caja.WSPrueba.crearFacturaResponse> crearFacturaAsync(hospital.Caja.WSPrueba.crearFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public hospital.Caja.WSPrueba.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(hospital.Caja.WSPrueba.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public hospital.Caja.WSPrueba.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(hospital.Caja.WSPrueba.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearFactura", Namespace="http://tempuri.org/", Order=0)]
        public hospital.Caja.WSPrueba.crearFacturaRequestBody Body;
        
        public crearFacturaRequest() {
        }
        
        public crearFacturaRequest(hospital.Caja.WSPrueba.crearFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crearFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id_seguro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string poliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telefono;
        
        public crearFacturaRequestBody() {
        }
        
        public crearFacturaRequestBody(string nombre, string cedula, int id_seguro, string poliza, string telefono) {
            this.nombre = nombre;
            this.cedula = cedula;
            this.id_seguro = id_seguro;
            this.poliza = poliza;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public hospital.Caja.WSPrueba.crearFacturaResponseBody Body;
        
        public crearFacturaResponse() {
        }
        
        public crearFacturaResponse(hospital.Caja.WSPrueba.crearFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class crearFacturaResponseBody {
        
        public crearFacturaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBDSoapChannel : hospital.Caja.WSPrueba.WSBDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBDSoapClient : System.ServiceModel.ClientBase<hospital.Caja.WSPrueba.WSBDSoap>, hospital.Caja.WSPrueba.WSBDSoap {
        
        public WSBDSoapClient() {
        }
        
        public WSBDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hospital.Caja.WSPrueba.HelloWorldResponse hospital.Caja.WSPrueba.WSBDSoap.HelloWorld(hospital.Caja.WSPrueba.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            hospital.Caja.WSPrueba.HelloWorldRequest inValue = new hospital.Caja.WSPrueba.HelloWorldRequest();
            inValue.Body = new hospital.Caja.WSPrueba.HelloWorldRequestBody();
            hospital.Caja.WSPrueba.HelloWorldResponse retVal = ((hospital.Caja.WSPrueba.WSBDSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hospital.Caja.WSPrueba.HelloWorldResponse> hospital.Caja.WSPrueba.WSBDSoap.HelloWorldAsync(hospital.Caja.WSPrueba.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<hospital.Caja.WSPrueba.HelloWorldResponse> HelloWorldAsync() {
            hospital.Caja.WSPrueba.HelloWorldRequest inValue = new hospital.Caja.WSPrueba.HelloWorldRequest();
            inValue.Body = new hospital.Caja.WSPrueba.HelloWorldRequestBody();
            return ((hospital.Caja.WSPrueba.WSBDSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hospital.Caja.WSPrueba.crearFacturaResponse hospital.Caja.WSPrueba.WSBDSoap.crearFactura(hospital.Caja.WSPrueba.crearFacturaRequest request) {
            return base.Channel.crearFactura(request);
        }
        
        public void crearFactura(string nombre, string cedula, int id_seguro, string poliza, string telefono) {
            hospital.Caja.WSPrueba.crearFacturaRequest inValue = new hospital.Caja.WSPrueba.crearFacturaRequest();
            inValue.Body = new hospital.Caja.WSPrueba.crearFacturaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.cedula = cedula;
            inValue.Body.id_seguro = id_seguro;
            inValue.Body.poliza = poliza;
            inValue.Body.telefono = telefono;
            hospital.Caja.WSPrueba.crearFacturaResponse retVal = ((hospital.Caja.WSPrueba.WSBDSoap)(this)).crearFactura(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hospital.Caja.WSPrueba.crearFacturaResponse> hospital.Caja.WSPrueba.WSBDSoap.crearFacturaAsync(hospital.Caja.WSPrueba.crearFacturaRequest request) {
            return base.Channel.crearFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<hospital.Caja.WSPrueba.crearFacturaResponse> crearFacturaAsync(string nombre, string cedula, int id_seguro, string poliza, string telefono) {
            hospital.Caja.WSPrueba.crearFacturaRequest inValue = new hospital.Caja.WSPrueba.crearFacturaRequest();
            inValue.Body = new hospital.Caja.WSPrueba.crearFacturaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.cedula = cedula;
            inValue.Body.id_seguro = id_seguro;
            inValue.Body.poliza = poliza;
            inValue.Body.telefono = telefono;
            return ((hospital.Caja.WSPrueba.WSBDSoap)(this)).crearFacturaAsync(inValue);
        }
    }
}
