//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IdCita { get; set; }
        public int IdCliente { get; set; }
        public Nullable<System.DateTime> FechaFormulario { get; set; }
        public string NombreServicio { get; set; }
    }
}
