//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int IdFactura { get; set; }
        public string NombreCompletoCliente { get; set; }
        public int CodigoFactura { get; set; }
        public Nullable<decimal> TotalFacturado { get; set; }
        public Nullable<decimal> TotalSeguro { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> TotalImporte { get; set; }
        public Nullable<bool> TransaccionConfirmada { get; set; }
    }
}
